spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: api-gateway

server:
  port: 8091

zuul:
  routes:
    a:
      path: /a/*
      serviceId: client-rcl
    b:
      path: /b/*
      serviceId: client-rcl2

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8088/eureka/




hystrix:
  command:
    default:
      execution:
        isolation:
          thread: 1000
        semaphore:
          maxConcurrentRequests: 100
    client-rcl2:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
          semaphore:
            maxConcurrentRequests: 50