spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
  application:
    name: api-gateway
  data:
    mongodb:
      uri: mongodb://localhost:27017/test

server:
  port: 8091


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8091/eureka/

